/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Transcription } from "./Transcription";
import { TranscriptionCountArgs } from "./TranscriptionCountArgs";
import { TranscriptionFindManyArgs } from "./TranscriptionFindManyArgs";
import { TranscriptionFindUniqueArgs } from "./TranscriptionFindUniqueArgs";
import { DeleteTranscriptionArgs } from "./DeleteTranscriptionArgs";
import { TranscriptionService } from "../transcription.service";
@graphql.Resolver(() => Transcription)
export class TranscriptionResolverBase {
  constructor(protected readonly service: TranscriptionService) {}

  async _transcriptionsMeta(
    @graphql.Args() args: TranscriptionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Transcription])
  async transcriptions(
    @graphql.Args() args: TranscriptionFindManyArgs
  ): Promise<Transcription[]> {
    return this.service.transcriptions(args);
  }

  @graphql.Query(() => Transcription, { nullable: true })
  async transcription(
    @graphql.Args() args: TranscriptionFindUniqueArgs
  ): Promise<Transcription | null> {
    const result = await this.service.transcription(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Transcription)
  async deleteTranscription(
    @graphql.Args() args: DeleteTranscriptionArgs
  ): Promise<Transcription | null> {
    try {
      return await this.service.deleteTranscription(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
