/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CallRecord } from "./CallRecord";
import { CallRecordCountArgs } from "./CallRecordCountArgs";
import { CallRecordFindManyArgs } from "./CallRecordFindManyArgs";
import { CallRecordFindUniqueArgs } from "./CallRecordFindUniqueArgs";
import { DeleteCallRecordArgs } from "./DeleteCallRecordArgs";
import { CallRecordService } from "../callRecord.service";
@graphql.Resolver(() => CallRecord)
export class CallRecordResolverBase {
  constructor(protected readonly service: CallRecordService) {}

  async _callRecordsMeta(
    @graphql.Args() args: CallRecordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CallRecord])
  async callRecords(
    @graphql.Args() args: CallRecordFindManyArgs
  ): Promise<CallRecord[]> {
    return this.service.callRecords(args);
  }

  @graphql.Query(() => CallRecord, { nullable: true })
  async callRecord(
    @graphql.Args() args: CallRecordFindUniqueArgs
  ): Promise<CallRecord | null> {
    const result = await this.service.callRecord(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CallRecord)
  async deleteCallRecord(
    @graphql.Args() args: DeleteCallRecordArgs
  ): Promise<CallRecord | null> {
    try {
      return await this.service.deleteCallRecord(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
